# Predict y with [x1,x2,x3]


In [31]:
import torch
import matplotlib as plt

In [32]:
# our ground truth model is y = w1*x1 + w2*x2 + w3*x3 +b
# [w1,w2,w3,b] = [3.5, 6, 2, 1]
w = torch.tensor([3.5, 6, 2])
b = torch.tensor([1])

In [60]:
# create artificial data
noise = torch.randn(1000,1)

x = torch.randn(1000,3)
y = torch.matmul(x,w).reshape(1000,1) + b + noise # y with noise
y.shape

torch.Size([1000, 1])

In [61]:
#our purpose is to learn w and b from data disturbed by noise

In [69]:
# divide our data into train and test set
x_train = x[0:500]
x_test = x[500:1000]
y_train = y[0:500]
y_test = y[500:1000]

In [70]:
model = torch.nn.Linear(3,1) # linear layer, with 3 of inputs, come out 1 output
model.weight, model.bias

(Parameter containing:
 tensor([[ 0.0509, -0.4877,  0.1968]], requires_grad=True),
 Parameter containing:
 tensor([-0.4735], requires_grad=True))

In [71]:
# train process

epochs = 40
lr = 0.14 #learning rate
criterion = torch.nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(),lr)

for epoch in range(epochs):
    
    optimizer.zero_grad()
    
    y_pred = model(x_train[epoch:epoch+25])
    loss = criterion(y_pred, y_train[epoch:epoch+25])
    
    loss.backward()
    optimizer.step()
    
    print('epoch {}, loss {}'.format(epoch, loss.item()))
    
    
    

epoch 0, loss 56.547603607177734
epoch 1, loss 29.768810272216797
epoch 2, loss 15.53900146484375
epoch 3, loss 8.475305557250977
epoch 4, loss 5.074153900146484
epoch 5, loss 3.154111385345459
epoch 6, loss 2.132913589477539
epoch 7, loss 1.5691184997558594
epoch 8, loss 1.1251182556152344
epoch 9, loss 0.8871534466743469
epoch 10, loss 0.7648993730545044
epoch 11, loss 0.7261290550231934
epoch 12, loss 0.7355553507804871
epoch 13, loss 0.572250247001648
epoch 14, loss 0.7143037915229797
epoch 15, loss 0.6578654646873474
epoch 16, loss 0.641740083694458
epoch 17, loss 0.6274204254150391
epoch 18, loss 0.5151606202125549
epoch 19, loss 0.6747156381607056
epoch 20, loss 0.6184413433074951
epoch 21, loss 0.6188164949417114
epoch 22, loss 0.6128202676773071
epoch 23, loss 0.587618350982666
epoch 24, loss 0.5489310622215271
epoch 25, loss 0.5152488350868225
epoch 26, loss 0.48614948987960815
epoch 27, loss 0.4670184254646301
epoch 28, loss 0.46842774748802185
epoch 29, loss 0.5362428426742

In [72]:
model.weight, model.bias

(Parameter containing:
 tensor([[3.7008, 5.7799, 2.1801]], requires_grad=True),
 Parameter containing:
 tensor([1.3947], requires_grad=True))

In [73]:
w, b

(tensor([3.5000, 6.0000, 2.0000]), tensor([1]))

# Summary



In [ ]:
# The performance would change if epoch and Learning rate is changed, these are hyper-parameters